#!/bin/bash
# -----------------------------------------------------------------------------
# Tool for searching and manipulating "notes" stored in markdown-formatted
# text files. See the USAGE section below for details on running this script.
#
# I recommend adding the following to your `.bashrc` (or equivalent):
#
#     export NOTEDIR=$HOME/Dropbox/Notes
#     export NOTEDEST=$HOME/Sites/Notes
#
#     alias notes-find="notes -a find"
#     alias notes-view="notes -a view"
#     alias notes-list="notes -a list"
#     alias notes-show="notes -a find -f"
#     alias notes-export="notes -a export"
#
# These alias make tab-completion a wee bit easier.
# -----------------------------------------------------------------------------

# Change these variables to suite yer fancy pants:

export OPENMETA=${OPENMETA:-openmeta}
export MARKDOWN=`type -p multimarkdown || type -p markdown`
export CONFIGDIR=${CONFIGDIR:-$HOME/.notes}
export NOTEDIR=${NOTEDIR:-$HOME/Dropbox/Notes}
export NOTEDEST=${NOTEDEST:-$HOME/Sites/Notes}

BOLD=`tput bold`
OFFBOLD=`tput init`

FORMAT=s  # This can be r for "raw", s for "simple", and f for "full"

EXTENSION_MATCHER='\.[^\.]*$'

# -----------------------------------------------------------------------------

USAGE="
This script searches through text files in the folder/directory:
    $NOTEDIR
as if they were *notes*. This script can help you search and manipulate them.

The first argument is an *action* that tells the script what to do:

  * list     - Lists all of the note filenames. Useful with -t option.
  * find     - Searches the notes that contain a particular string
  * view     - Converts a markdown formatted note into HTML. Opens in browser.
  * all-tags - List all of the tags used in all notes.
  * export   - Export some notes as HTML into the directory:
                   $NOTEDEST

The command actions accept the following parameters:

   -a <action> for specifying the action or command to do.
   -n <name>   for working with files whose names match this argument
   -t <tags>   for working with files that have all the tags given
   -d <dir>    for specifying the export destination (overrides $NOTEDEST)
   -r          for raw output format (full note names and whatnot)
   -p          for print-printing the output (trimmed filenames)
   -f          for displaying the entire note
"
# -----------------------------------------------------------------------------

if [ "-z" '<' "$1" ]    # The first argument could be the action
then                    # unless the first argument is a dash option
    ACTION=$1;
    shift 1
fi

# Let's part the command-line arguments looking for options:
#   -a <action> for specifying the action or command to do.
#   -n <name>   for working with files that match a filename
#   -t <tag>    for specifying a tag
#   -d <dest>   for overriding the NOTEDEST variable
#   -r          for raw output format (full note names and whatnot)
#   -p          for print-printing the output (trimmed filenames)

while getopts "a:t:n:d:rpf" o
do  case "$o" in
        a)  ACTION="$OPTARG";;
        t)  TAGS="$OPTARG";;
        n)  NAMES="$OPTARG";;
        d)  NOTEDEST="$OPTARG";;
        r)  FORMAT=r;;
        p)  FORMAT=p;;
        f)  FORMAT=f;;
      [?])  echo >&2 "Usage: $0 [-a] <action> [-r|-p] [-t <tags>] ..."
            echo >&2 "$USAGE"
            exit 1;;
    esac
done
shift `expr $OPTIND - 1`

if [ -z "$ACTION" ]     # If we still haven't been given an action,
then                    # we assume the first string after the options
    ACTION=$1           # is the action.
    shift 1
fi

# -----------------------------------------------------------------------------
# Helpful functions. Skip to the end to see us call these functions.
# -----------------------------------------------------------------------------


#
# Passing in a filename, this will return the tags associated with it.
# Basically a simplified wrapper around the openmeta program.
# Call it with backticks: `getTags "$FILENAME"`
#
function getTags() {
    ${OPENMETA:-openmeta} -t -p "$*" | sed 's/\/.*$//'
}

#
# This function will search the notes directory for files that match particular
# name patterns and return this list. This makes all of the programs behave the
# same way.
#
function getAllNotes() {
    local STAR='*'
    if [ -n "$NAMES" ]; then
        STAR="*$NAMES*"
    fi
set -x
    find "$NOTEDIR" \( -iname "$STAR.txt" -or -iname "$STAR.markdown" -or -iname "$STAR.md" \) -and \! -iname "*conflicted copy*" -and \! -iname "Interim Note-Changes*" -and \! -iname 'Notes & Settings*'
}

#
# Similar to getAllNotes, but limits the the full names returned to those files
# that contain all the tags specified on the command line "-t" option.
#
function getNotes() {
    if [ -z "$TAGS" -a -z "$NAMES" ]   # Optimization
    then
        getAllNotes
    else
        getAllNotes | while read FILE
        do
            local GOT_TAGS=0
            local GOT_NAMES=0

            if [ -n "$TAGS" ]; then
                if getTags "$FILE" | grep "$TAGS" >/dev/null
                then
                    GOT_TAGS=1
                fi
            else
                GOT_TAGS=1
            fi

            if [ -n "$NAMES" ]; then
                if echo "$FILE" | grep "$NAMES"; then
                    GOT_NAMES=1
                fi
            else
                GOT_NAMES=1
            fi

            if [ "$GOT_TAGS" = "1" -a "$GOT_NAMES" = "1" ]
            then
                echo "$FILE"
            fi
        done
    fi
}

#
# Trims a filename to just the basename regardless of the extension that
# may be associated with it.
#
function baseName() {
    basename "$*" | sed "s/$EXTENSION_MATCHER//"
}

# -----------------------------------------------------------------------------

#
# List the filenames in the notes directory. This can be limited by
# tags. Otherwise, we either print the full filename (in raw mode),
# or just the names of the files (without extensions) in pretty mode.
#
function listFiles() {
    case "$FORMAT" in
        r)  getNotes;;
        *)  getNotes | while read FILE
            do
                baseName "$FILE"
            done
    esac
}

#
# Uses egrep to look through either all files or only the files that
# match a particular tag. In pretty mode, we display some of the
# context.
#
function findFiles() {
    export SEARCH="$*"

    case "$FORMAT" in
        r)
            GREP="egrep --files-with-matches --ignore-case"
            getNotes | while read FILE
            do
                $GREP "$SEARCH" "$FILE"
            done
            ;;
        s)
            GREP="egrep --context=1 --color=always --ignore-case --max-count=1"
            
            getNotes | while read FILE
            do
                RESULTS=`$GREP "$SEARCH" "$FILE"`
                if [ $? -eq 0 ]
                then
                    echo $BOLD`baseName "$FILE"`$OFFBOLD
                    echo "$RESULTS" | sed 's/^/  /'
                    echo
                elif echo "$FILE" | grep --ignore-case "$SEARCH" >/dev/null
                then
                    echo $BOLD`baseName "$FILE"`$OFFBOLD
                    echo
                fi
            done | ${PAGER:-less -r}
            ;;
        f)
            GREP="egrep --ignore-case --files-with-matches"
            PAGER_OPTS="-r"
            if [ -n "$SEARCH" ]; then
                PAGER_OPTS="-r --pattern='$SEARCH'"
            fi
            getNotes | while read FILE
            do
                if ( $GREP "$SEARCH" "$FILE" || echo "$FILE" | grep --ignore-case "$SEARCH" ) >/dev/null 2>&1
                then
                    echo
                    echo "-------------------------------------------------------------"
                    echo $BOLD`baseName "$FILE"`$OFFBOLD
                    echo "-------------------------------------------------------------"
                    cat "$FILE"
                fi
            done | ${PAGER:-less} "$PAGER_OPTS"
            ;;
    esac
}

#
# Loop over all of the matching files offering to convert and
# display each one. Useful only if -t and -n options. ;-)
#
function viewFiles() {
    SAVEIFS=$IFS
    IFS=$(echo -en "\n\b")
    IDX=0

    for FILE in `getNotes`
    do
        BASE=`baseName "$*"`
        echo -n "Found '$BASE'. Use it? [y/n] "
        read answer
        if [ "$answer" = "y" ]
        then
            OUT="/tmp/exported-note-$IDX.html"
            $MARKDOWN --output "$OUT" "$FILE"
            open -F "$OUT"
            IDX=`expr $IDX + 1`
        fi
    done

    IFS=$SAVEIFS
}

#
# Loops through all specified files and converts them into HTML
# using markdown. It writes them into the $DIRDEST directory.
#
function exportFiles() {
    TEMPLATE=$(cat $CONFIGDIR/template.html)
    getNotes | while read FILE
    do
        TITLE=$(baseName $FILE)
        NEW=$(baseName "$FILE" | sed 's/ /-/g')
        OUT="$NOTEDEST/$NEW.html"
        BODY=$($MARKDOWN "$FILE")

        export STYLES=""
        export SCRIPTS=""
        for T in $(getTags "$FILE")
        do
            if [ -f "$NOTEDEST/css/$T.css" ]
            then
                STYLES="$STYLES<link type='text/css' href='css/$T.css' rel='stylesheet'/>"
            fi
            if [ -f "$NOTEDEST/js/$T.js" ]
            then
                SCRIPTS="$SCRIPTS<script type='text/javascript' href='js/$T.js'></script>"
            fi
        done

        echo "Creating $OUT"

        # Why sure we could use a fancy templating language, but that wouldn't
        # be necessary for such a simple task as this. We'll just use perl.
        echo $TEMPLATE \
            | perl -p -e "s|\{\{TITLE\}\}|$TITLE|g; s|\{\{STYLES\}\}|$STYLES|g; s|\{\{SCRIPTS\}\}|$SCRIPTS|g; s|\{\{BODY\}\}|${BODY}|g"       > "$OUT"
    done
}

function listTags() {
    echo "TODO: List all the tags used."
}

# -----------------------------------------------------------------------------
# Call the function based on a command action given to us:

case "$ACTION" in
    find|grep)          # Searches the notes that contain a particular string
        findFiles "$*";;

    list)               # Lists all of the notes.
        listFiles;;

    view)               # Converts a markdown formatted note into HTML.
        viewFiles $*;;

    "export")           # Export some notes as HTML into a directory.
        exportFiles;;

    all-tags)           # List all of the tags used in all notes.
        listTags;;

    *)
        echo >&2 "No action specified."
        echo >&2 "Usage: $0 [-a] <action> [-r|-p] [-t <tags>] ..."
        echo >&2 "$USAGE"
        exit 1;;
esac
